# Generated by Django 5.0.1 on 2024-03-06 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('url_twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('url_facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('url_github', models.CharField(blank=True, max_length=100, null=True)),
                ('url_youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('url_linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
