# Generated by Django 5.0.1 on 2024-03-06 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datausuario',
            name='imagen',
        ),
    ]
