# Generated by Django 5.0.1 on 2024-03-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0005_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='contenido',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
