# Generated by Django 5.0.1 on 2024-03-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0007_educacion_experiencialaboral_idiomas'),
    ]

    operations = [
        migrations.AddField(
            model_name='datausuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datausuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
