# Generated by Django 5.0.1 on 2024-03-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0009_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones'),
        ),
    ]
